"""
Gift hampers: editable copy, the public listing, and admin SCRUD.

A hamper is a document in db.books with product_type="hamper" (see the note on
the Book model in server.py for why). This module owns the parts that are not
book-shaped: the wording on the page, which is entirely admin-editable, and the
create/read/update/delete screens behind it.

WHY EVERY STRING IS A FIELD
Marketing copy on a seasonal product changes between the mock-up and the
launch, and again the morning after. Hard-coding "What's inside" means a
one-line change, a commit, a review and a deploy to fix a typo on a page that
is live for eleven days. So every visible string is a key in `hamper_copy`,
defaulted here and overridable per hamper.

THE OVERRIDE TRAP
Defaults below apply only where the stored document has no value for that key.
Once a key has been saved from Admin -- even to the same string -- editing the
default here stops changing the live page, because the stored value wins. This
has caught us before on site content. To genuinely reset a key, clear it in
Admin; do not edit this file and expect the site to move.
"""
from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, ConfigDict, Field

from extensions import db, require_admin

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Editable copy
# ---------------------------------------------------------------------------
# {value} and {stock} are the only placeholders. They are substituted at render
# time in the browser, not here, so an admin can move them around inside a
# sentence or drop them entirely without the server needing to know.
HAMPER_COPY_DEFAULTS: dict = {
    "eyebrow": "Gift hamper",
    "value_note": "Bought separately, the contents come to {value}.",
    "stock_note": "Only {stock} boxes left",
    "contents_heading": "What's inside",
    "contents_value_heading": "Value",
    "contents_badge": "From the catalogue",
    "gift_heading": "Send it as a gift",
    "gift_message_label": "Message on the card",
    "gift_message_hint": "up to 200 characters",
    "gift_message_placeholder": "Write what you'd say if you were handing it over.",
    "recipient_label": "Recipient's name, as it should appear",
    "recipient_placeholder": "Their name",
    "deliver_elsewhere_label": "Deliver to a different address",
    "deliver_elsewhere_note": "You'll enter theirs at checkout. The invoice comes to you — no price goes in the box.",
    "add_to_cart_label": "Add to Cart",
    "buy_now_label": "Buy Now",
    "delivery_note": "Dispatched in 1 business day. Delivery 3–7 business days across India.",
    "order_by_label": "Order by {date}",
    "assurances": [
        {"label": "Free delivery", "value": "Boxed, wrapped and insured in transit"},
        {"label": "No price in the box", "value": "The invoice goes to you, not to them"},
        {"label": "14-day returns", "value": "Unopened boxes, no questions"},
    ],
    "bulk_heading": "Sending more than five?",
    "bulk_text": "Chambers, firms and in-house teams — your imprint on the card, your "
                 "choice of titles, delivered to one address or a hundred different ones.",
    "bulk_cta": "Talk to us about bulk gifting",
    "bulk_link": "/contact",
}

# The listing page at /gifting. Site-wide rather than per hamper, so it lives in
# settings under this key.
GIFTING_PAGE_DEFAULTS: dict = {
    "eyebrow": "Oakbridge Gifting",
    "heading": "Books, boxed and ready to give.",
    "lede": "Hampers put together by our editors — a couple of titles worth keeping, "
            "and the small things that make them feel given rather than ordered.",
    "empty": "No hampers are on sale just now. Do come back.",
}

# The banner is a photograph the admin uploads, not a composed layout. `alt` is
# required by the img-alt sanity check and by anyone using a screen reader, and
# `image_mobile` exists because a wide hero crop is unreadable at 390px.
BANNER_DEFAULTS: dict = {
    "enabled": False,
    "image": "",
    "image_mobile": "",
    "alt": "",
    "link": "/gifting",
    # above_hero puts it before the masthead image, which is the most prominent
    # slot on the site; below_hero drops it into the ordinary section order where
    # it can be dragged like any other block. Editable because "top of the page"
    # is a marketing decision that changes per campaign, not a layout constant.
    "position": "below_hero",   # above_hero | below_hero
    # Desktop cap in px. A full-width photograph at its natural aspect ratio is
    # roughly 500px tall at 1600px wide, which pushes everything else below the
    # fold. Capped and cropped from the centre rather than squashed.
    "max_height": 320,
}


def merge_copy(stored: Optional[dict]) -> dict:
    """Defaults, with the admin's saved strings on top. Blank means 'use default'."""
    out = dict(HAMPER_COPY_DEFAULTS)
    for k, v in (stored or {}).items():
        if v is None:
            continue
        # A string the admin has emptied falls back to the default rather than
        # rendering a blank label — an unlabelled field is worse than a generic
        # one, and "clear it to reset it" is the behaviour the docstring promises.
        if isinstance(v, str) and not v.strip():
            continue
        out[k] = v
    return out


def decorate_hamper(doc: dict) -> dict:
    """Fill in the copy for a hamper on its way out. No-op for a book."""
    if doc and doc.get("product_type") == "hamper":
        doc["hamper_copy"] = merge_copy(doc.get("hamper_copy"))
    return doc


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------
class HamperItem(BaseModel):
    model_config = ConfigDict(extra="ignore")
    book_id: Optional[str] = None   # set => a catalogue title, and stock moves with it
    label: str = ""                 # used when book_id is empty
    note: str = ""
    image: str = ""
    value: float = 0
    qty: int = 1


class HamperCreate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    title: str
    subtitle: Optional[str] = None
    description: str = ""
    price: float
    original_price: Optional[float] = None
    cover_image: str = ""
    gallery: list = Field(default_factory=list)
    sku: Optional[str] = None
    stock: int = 0
    occasion: Optional[str] = None
    order_by: Optional[str] = None
    hamper_items: list = Field(default_factory=list)
    hamper_copy: dict = Field(default_factory=dict)
    gift_message_enabled: bool = True
    bulk_enquiry: bool = True
    enabled: bool = True
    order: int = 0


class HamperUpdate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    title: Optional[str] = None
    subtitle: Optional[str] = None
    description: Optional[str] = None
    price: Optional[float] = None
    original_price: Optional[float] = None
    cover_image: Optional[str] = None
    gallery: Optional[list] = None
    sku: Optional[str] = None
    stock: Optional[int] = None
    occasion: Optional[str] = None
    order_by: Optional[str] = None
    hamper_items: Optional[list] = None
    hamper_copy: Optional[dict] = None
    gift_message_enabled: Optional[bool] = None
    bulk_enquiry: Optional[bool] = None
    enabled: Optional[bool] = None
    order: Optional[int] = None


# ---------------------------------------------------------------------------
# Public
# ---------------------------------------------------------------------------
public_router = APIRouter(prefix="/api", tags=["hampers"])


async def _hydrate(doc: dict) -> dict:
    """Fill each contents line that points at a catalogue title.

    Cover, title, author and price are read live rather than copied in at build
    time, so a hamper cannot end up advertising last season's price for a book
    whose price moved. Only `value` is respected as an override, because the
    value of a title inside a bundle is an editorial choice, not the sale price.
    """
    doc = decorate_hamper(doc)
    ids = [i.get("book_id") for i in doc.get("hamper_items", []) if i.get("book_id")]
    books = {}
    if ids:
        rows = await db.books.find(
            {"id": {"$in": ids}},
            {"_id": 0, "id": 1, "title": 1, "author": 1, "cover_image": 1,
             "price": 1, "original_price": 1, "binding": 1, "stock": 1},
        ).to_list(None)
        books = {r["id"]: r for r in rows}

    out = []
    for item in doc.get("hamper_items", []):
        row = dict(item)
        src = books.get(item.get("book_id") or "")
        if src:
            row["label"] = src.get("title") or row.get("label") or ""
            row["note"] = row.get("note") or " · ".join(
                x for x in [src.get("author"), src.get("binding")] if x
            )
            row["image"] = src.get("cover_image") or ""
            row["is_book"] = True
            row["component_stock"] = src.get("stock", 0)
            if not row.get("value"):
                row["value"] = src.get("original_price") or src.get("price") or 0
        else:
            row["is_book"] = False
            # A line pointing at a title that has since been deleted would
            # otherwise render as a nameless empty row on a live sales page.
            if item.get("book_id") and not row.get("label"):
                row["label"] = "(this title is no longer in the catalogue)"
                row["missing"] = True
        out.append(row)
    doc["hamper_items"] = out
    doc["contents_value"] = sum(
        float(r.get("value") or 0) * int(r.get("qty", 1) or 1) for r in out
    )
    return doc


@public_router.get("/hampers")
async def list_hampers():
    docs = await db.books.find(
        {"product_type": "hamper", "enabled": {"$ne": False}}, {"_id": 0}
    ).sort("order", 1).to_list(None)
    return [await _hydrate(d) for d in docs]


@public_router.get("/hampers/{hamper_id}")
async def get_hamper(hamper_id: str):
    doc = await db.books.find_one(
        {"id": hamper_id, "product_type": "hamper"}, {"_id": 0}
    )
    if not doc:
        raise HTTPException(status_code=404, detail="Hamper not found")
    return await _hydrate(doc)


# ---------------------------------------------------------------------------
# Admin
# ---------------------------------------------------------------------------
admin_router = APIRouter(
    prefix="/api/admin", tags=["admin-hampers"], dependencies=[Depends(require_admin)]
)


@admin_router.get("/hampers")
async def admin_list_hampers(q: str = "", enabled: str = "all"):
    query: dict[str, Any] = {"product_type": "hamper"}
    if enabled == "on":
        query["enabled"] = {"$ne": False}
    elif enabled == "off":
        query["enabled"] = False
    docs = await db.books.find(query, {"_id": 0}).sort("order", 1).to_list(None)
    needle = q.strip().lower()
    if needle:
        docs = [
            d for d in docs
            if needle in (d.get("title", "") + " " + (d.get("sku") or "")
                          + " " + (d.get("occasion") or "")).lower()
        ]
    out = []
    for d in docs:
        h = await _hydrate(d)
        # Surfaced so the list can warn before a box is oversold: 40 hampers
        # promising a title with 12 copies left is a packing problem discovered
        # at the worst possible moment.
        h["short_components"] = [
            i["label"] for i in h["hamper_items"]
            if i.get("is_book") and i.get("component_stock", 0) < d.get("stock", 0)
        ]
        out.append(h)
    return {"count": len(out), "hampers": out}


@admin_router.post("/hampers")
async def admin_create_hamper(payload: HamperCreate):
    doc = {
        "id": str(uuid.uuid4()),
        **payload.model_dump(),
        "product_type": "hamper",
        # Book-shaped fields the rest of the app still reads. A hamper has no
        # author, ISBN or page count; these keep every consumer that prints them
        # working without teaching each one about a new product type.
        "author": "",
        "isbn": "",
        "pages": 0,
        "category": "gifting",
        "subject": "Gifting",
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    await db.books.insert_one(dict(doc))
    log.info("Hamper created: %s (%s)", doc["title"], doc["id"])
    return await _hydrate({k: v for k, v in doc.items() if k != "_id"})


@admin_router.patch("/hampers/{hamper_id}")
async def admin_update_hamper(hamper_id: str, payload: HamperUpdate):
    updates = {k: v for k, v in payload.model_dump().items() if v is not None}
    if not updates:
        raise HTTPException(status_code=400, detail="Nothing to update")
    res = await db.books.update_one(
        {"id": hamper_id, "product_type": "hamper"}, {"$set": updates}
    )
    if res.matched_count == 0:
        raise HTTPException(status_code=404, detail="Hamper not found")
    doc = await db.books.find_one({"id": hamper_id}, {"_id": 0})
    return await _hydrate(doc)


@admin_router.delete("/hampers/{hamper_id}")
async def admin_delete_hamper(hamper_id: str):
    # Scoped to product_type so a mistyped id can never reach a book. Orders
    # keep their own snapshot of what was bought, so deleting a sold-out hamper
    # does not disturb anyone's receipt or packing slip.
    res = await db.books.delete_one({"id": hamper_id, "product_type": "hamper"})
    if res.deleted_count == 0:
        raise HTTPException(status_code=404, detail="Hamper not found")
    log.info("Hamper deleted: %s", hamper_id)
    return {"deleted": True, "id": hamper_id}


class ReorderRequest(BaseModel):
    ids: list


@admin_router.post("/hampers/reorder")
async def admin_reorder_hampers(payload: ReorderRequest):
    for i, hid in enumerate(payload.ids):
        await db.books.update_one(
            {"id": hid, "product_type": "hamper"}, {"$set": {"order": i}}
        )
    return {"ok": True, "count": len(payload.ids)}


@admin_router.get("/hampers-copy-defaults")
async def admin_copy_defaults():
    """So the admin form renders every editable string without a second copy of
    the list living in the frontend, drifting."""
    return {"copy": HAMPER_COPY_DEFAULTS, "page": GIFTING_PAGE_DEFAULTS,
            "banner": BANNER_DEFAULTS}
