/**
 * Built-in default copy for every admin-editable site_content text slot.
 *
 * WHY THIS EXISTS: the storefront renders `site.<key> || "<default>"`, so when no
 * override is saved the DB holds nothing and the admin field looked EMPTY even
 * though the live page showed text. The admin now uses these values as
 * placeholders, so an empty field visibly means "using the built-in default"
 * rather than "this section has no content".
 *
 * An empty override deliberately falls back to the default, so clearing a field
 * in the admin restores the text below.
 *
 * Keys mirror the site_content keys. Most were extracted from the page
 * components; a handful whose defaults are JSX fragments are transcribed using
 * the *highlight* convention that renderRich understands.
 */
const CONTENT_DEFAULTS = {
    ebook_enabled: "on",
    ebook_url: "https://ebooks.oakbridge.in/",
    ebook_cta_label: "Interested in e-books?",
    ebook_cta_action: "Read on Oakbridge eReader",
    ebook_cta_blurb: "Read Oakbridge titles on any device — searchable, annotatable and always with you.",
    about_body1: "Oakbridge Publishing was founded in 2017 by two veteran publishing professionals with leadership experience at some of the world's most respected publishing companies. The premise was simple — India deserves its own scholarly voice, published from within, for the students, educators and practitioners who live here. We publish across five imprints: Academic, Professional, General, Coffee Table and Curated Works. Every manuscript is shepherded by editors with decades of international publishing experience.",
    about_body2: "We remain a privately-held, independent publisher — which means our editorial choices are made by readers and educators, not shareholders.",
    about_overline: "About Oakbridge",
    about_team_overline: "Our Management Team",
    about_team_title: "The people behind\nthe imprint.",
    about_timeline_overline: "Our Timeline",
    about_timeline_title: "Eight years, many states,\none standard.",
    about_title: "A modern press\nfor a *country*\nbeing rewritten.",
    ac_accent: "authors you read.",
    ac_body: "The Oakbridge Academy is a new home for self-paced e-learning, certification programmes and in-house workshops — drawing from the same practitioner-authors who write our reference titles. Cohorts open soon.",
    ac_eyebrow: "Oakbridge · Academy",
    ac_features_headline: "Three formats.\nOne goal — Learn.",
    ac_features_kicker: "What's coming",
    ac_headline: "Practitioner training,\ntaught by the",
    authors_overline: "Our Authors",
    authors_title: "The scholars, teachers\nand storytellers\nbehind our list.",
    careers_body: "We hire editors, salespeople, designers and technologists who believe publishing is a craft of public service. See our open roles, or send us a general application — we're always glad to meet good people.",
    careers_overline: "Careers",
    careers_title: "Build the house that publishes India.",
    contact_body: "Questions about our books, bulk orders for your school, press inquiries, or manuscripts — reach us through the form below or at the addresses to the right.",
    contact_overline: "Get in Touch",
    contact_title: "We read every letter.",
    ds_accent: "books you trust.",
    ds_body: "We're building a new line of digital products on top of Oakbridge's scholarly catalogue — semantic search, research copilots and licensed APIs for law firms, universities and Corporate & Judiciary. Launching soon.",
    ds_eyebrow: "Oakbridge · Digital Solutions",
    ds_features_headline: "Three products.\nOne trusted source.",
    ds_features_kicker: "What's coming",
    ds_headline: "AI-powered research,\nbuilt on the",
    events_cta_body: "Whether you're a delegate, a sponsor seeking a high-impact platform, or a thought leader with something to say — there's a place for you at Oakbridge events.",
    events_cta_overline: "Get involved",
    events_cta_title: "Register, partner\nor speak.",
    events_exp_overline: "The Experience",
    events_exp_title: "Experience law & ideas\nlike never before.",
    events_hero_body: "Vidhi Utsav — a celebration of Law & Literature — and the India Law, AI & Tech Summit on the future of legal innovation. Oakbridge curates the country's most influential gatherings convening judges, jurists, general counsels, scholars and technologists.",
    events_hero_overline: "Oakbridge Events",
    events_hero_title: "Two curated\n*flagship events.*",
    events_summit_overline: "Summit Speakers",
    events_summit_title: "The future of law,\non one stage.",
    events_vidhi_overline: "Vidhi Utsav Speakers",
    events_vidhi_title: "Eminent voices on stage.",
    events_who_body: "Oakbridge events are invitation-rich, deliberately small and built for the people shaping legal practice and policy in India and beyond.",
    events_who_overline: "Who attends",
    events_who_title: "A curated gathering\nof luminaries.",
    footer_blurb: "Oakbridge Publishing crafts scholarly and educational titles for classrooms, libraries and curious readers across India and beyond.",
    footer_copyright: "Oakbridge Publishing Pvt. Ltd. — ISBN Registrar 978-81-XXXX.",
    footer_est: "Est. 2017 · New Delhi",
    footer_news_button: "Subscribe",
    footer_news_placeholder: "your@email.com",
    footer_news_success: "Welcome to the Oakbridge reading list.",
    footer_tagline: "Books that teach.\nIdeas that travel.",
    home_bestsellers_overline: "Bestsellers",
    home_bestsellers_title: "What leaders are reading.",
    home_biz_overline: "Our Businesses",
    home_biz_title: "Four complementary lines of business.",
    home_hero_body: "Oakbridge produces authoritative, reliable and opinion-influencing reference titles, legal commentaries, thematic books across various genres, and thought-leadership curated works for students, professionals and curious minds across the globe.",
    home_hero_overline: "Est. 2017 · A Scholarly Press",
    home_hero_title: "A library for\nthe *intellectually*\nrestless.",
    home_hot_overline: "Hot Off the Press",
    home_hot_title: "New this season.",
    home_imprints_overline: "The Catalogue",
    home_imprints_title: "Five imprints.\nOne scholarly standard.",
    home_solutions_body: "We collaborate with professionals and scholars to curate opinion-building books that empower readers and users to gain a competitive edge.",
    home_solutions_overline: "Solutions",
    home_solutions_title: "We work with the institutions shaping tomorrow.",
    home_stat1_label: "Titles in print",
    home_stat1_value: "230+",
    home_stat2_label: "Students served",
    home_stat2_value: "320K",
    home_stat3_label: "Reach",
    home_stat3_value: "Global",
    home_testimonials_overline: "Testimonials",
    home_testimonials_title: "What readers say.",
    media_body: "Photographs and film from our launches, forums and summits — the people and ideas shaping law, policy and scholarship in India.",
    media_events_title: "Events",
    media_launches_title: "Book Launches",
    media_overline: "Media & Gallery",
    media_presentations_title: "Book Presentations",
    media_title: "Moments from the *Oakbridge* stage.",
    plp_stat1_value: "190+",
    plp_stat1_label: "titles",
    plp_stat2_value: "5",
    plp_stat2_label: "imprints",
    plp_hero_body: "Browse authoritative reference titles, legal commentaries, curated thematic works and scholarly editions from Oakbridge Publishing — all in one place.",
    plp_hero_overline: "The Bookstore",
    plp_hero_title: "A library for the\n*intellectually* curious.",
    solutions_cta_label: "Talk to our institutional team",
    solutions_included_label: "What's included",
    solutions_index_overline: "Institutional Solutions",
    solutions_index_title: "Partners to\neducators, schools\nand institutions.",
    sub_body: "Oakbridge is actively commissioning across Academic, Law, Tax, Business and Reference lists. Share your book idea below and our editorial team will respond within four weeks.",
    sub_lookfor_items: "Original, well-structured scholarship\nClear pedagogical intent and audience\nA sample chapter or complete manuscript\nAuthor credentials & teaching experience",
    sub_lookfor_title: "What we look for",
    sub_overline: "Author Submissions",
    sub_title: "We read every\nmanuscript.",
    wwd_body: "Oakbridge started as a publisher. Today we span four complementary businesses — all anchored by the same authoritative content, authors and editorial standards.",
    wwd_highlight: "centre of gravity.",
    wwd_overline: "What We Do",
    wwd_title: "Four businesses.\nOne scholarly",
};

export default CONTENT_DEFAULTS;
